// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rdywqlswesvpolsvgiyd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJkeXdxbHN3ZXN2cG9sc3ZnaXlkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE3NzI2NjksImV4cCI6MjA2NzM0ODY2OX0.VMoJqHVIR9j-ntqmW9ufD9UmGdecQnAWh8xgyTqfky4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});